# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CordovaEmbeddedPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CordovaEmbeddedPod
  pod 'Cordova' # Cordova framework and plugins
  pod 'CordovaPlugin-console'
  pod 'cordova-plugin-camera'
  pod 'cordova-plugin-contacts'
  pod 'cordova-plugin-device'
  pod 'cordova-plugin-device-orientation'
  pod 'cordova-plugin-device-motion'
  pod 'cordova-plugin-globalization'
  pod 'cordova-plugin-geolocation'
  pod 'cordova-plugin-file'
  pod 'cordova-plugin-media-capture'
  pod 'cordova-plugin-network-information'
  pod 'cordova-plugin-splashscreen'
  pod 'cordova-plugin-inappbrowser'
  pod 'cordova-plugin-file-transfer'
  pod 'cordova-plugin-statusbar'
  pod 'cordova-plugin-vibration'
  pod 'cordova-plugin-wkwebview-engine'
  pod 'phonegap-ios-template' # Cordova template 

  target 'CordovaEmbeddedPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
